public with sharing class Abcd {
    public Abcd() 
    {
        System.debug('hello');
        System.debug('After Github fetch');
        System.debug('Changes in github GUI');
        System.debug('Again i m changing for practice in github');
        System.debug('i m Changing in vs cod');
        System.debud('This is last from github');
        System.debug('This is last from Vs code');
        System.debug('Now end to check local machine')'
    }

}
