public class Z_Basic_CreateContactAcc{
    public Z_Basic_CreateContactAcc(){
       system.debug('hello'); 
    }    
}

/* you can create account or contact by using this code in debug window
Account c = new Account();
c.name='Fifth Account';
insert c;
system.debug('Id is' +c.id);*/

/*contact c = new contact();
c.firstname='Jon';
c.lastname='jonny';
c.email='jon@gmail.com';
insert c;
system.debug('Id is' +c.id);*/