public class Z_DataTypes_Primitive 
{
    public static void mymethod2()
    {
        integer a=10;
        string b= 'mystring';
        double c=234;
        long d=36475684L;
        decimal e =22.4;
        double f=334.4;
        system.debug(a);
        system.debug(f);
        
        date d1;
        d1=date.today();
        system.debug(d1);
        
        ID pp = '098gd5643j897df';
        system.debug(pp);
       
        
    }

    
}